=== mycsHQ/mycs-hash/src/json-schemas/image-input-data.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "required": [ "structure", "quality", "stage", "camera" ],
  "properties": {
    "structure": {
      "oneOf": [
        { "type": "object" },
        { "type": "array" }
      ]
    },
    "quality": {
      "type": "string",
      "enum": [ "label", "normal", "hires" ]
    },
    "stage": {
      "type": "string",
      "minLength": 1
    },
    "camera": {
      "type": "object",
      "additionalProperties": false,
      "required": [ "vAngle" ],
      "properties": {
        "fov": { "type": "number" },
        "angle": { "type": "number" },
        "hAngle": { "type": "number" },
        "vAngle": { "type": "number" },
        "distance": { "type": "number" },
        "autozoom": { "type": "boolean" },
        "height": { "type": "number" },
        "width": { "type": "number" }
      }
    },
    "processing": {
      "type": "object",
      "additionalProperties": false,
      "required": [ "noise", "samples" ],
      "properties": {
        "noise": { "type": "number" },
        "samples": { "type": "number" },
        "floor": { "type": "array" },
        "no_intermediate": { "type": "boolean" },
        "floor_luminance": { "type": "number" },
        "envmap_name": { "type": "string" },
        "exposure": { "type": "number" },
        "gamma": { "type": "number" },
        "hist_min": { "type": "number" },
        "hist_max": { "type": "number" }
      }
    },
    "animation": {
      "type": "object",
      "additionalProperties": false,
      "required": [ "numberOfFrames", "alpha" ],
      "properties": {
        "numberOfFrames": { "type": "number" },
        "alpha": { "type": "number" }
      }
    }
  }
}

=== mycsHQ/mycs-hash/src/tests/structures/wardrobe.json
{
  "camera": {
    "angle": 0,
    "vAngle": 0
  },
  "quality": "hires",
  "stage": "default",
  "structure": {
    "outer_wall_left": {
      "sku": "102.105.00"
    },
    "outer_wall_right": {
      "sku": "102.105.00"
    },
    "columns": [
      {
        "corpus": {
          "sku": "401.100.04"
        },
        "boards": [
          {
            "sku": "102.103.00",
            "z": 38.3
          },
          {
            "z": 76.7,
            "sku": "102.103.00"
          },
          {
            "z": 153.5,
            "sku": "102.103.00"
          }
        ],
        "doors": [
          {
            "door": {
              "sku": "102.107.08"
            },
            "handles": [
              {
                "sku": "102.108.00"
              },
              {
                "sku": "102.108.02"
              }
            ]
          }
        ],
        "backwall": {
          "sku": "000.002.08"
        },
        "drawers": [
          {
            "sku": "401.100.164",
            "z": 147
          }
        ],
        "cluster": 0
      },
      {
        "corpus": {
          "sku": "401.100.04"
        },
        "boards": [
          {
            "sku": "102.103.00",
            "z": 38.3
          },
          {
            "z": 76.7,
            "sku": "102.103.00"
          }
        ],
        "doors": [
          {
            "door": {
              "sku": "102.107.00"
            },
            "handles": [
              {
                "sku": "102.108.00"
              },
              {
                "sku": "102.108.00"
              }
            ]
          }
        ],
        "backwall": {
          "sku": "000.002.08"
        },
        "drawers": [
          {
            "sku": "401.100.134",
            "z": 3
          },
          {
            "sku": "401.100.134",
            "z": 22.2
          },
          {
            "sku": "401.100.134",
            "z": 41.4
          },
          {
            "sku": "401.100.134",
            "z": 60.6
          },
          {
            "sku": "401.100.126",
            "z": 79.8
          }
        ],
        "lifts": [
          {
            "sku": "401.100.117",
            "z": 213.5
          }
        ],
        "cluster": 0
      },
      {
        "corpus": {
          "sku": "401.100.04"
        },
        "boards": [
          {
            "sku": "102.103.00",
            "z": 38.3
          },
          {
            "z": 76.7,
            "sku": "102.103.00"
          },
          {
            "z": 115.1,
            "sku": "102.103.00"
          },
          {
            "z": 153.5,
            "sku": "102.103.00"
          },
          {
            "z": 191.9,
            "sku": "102.103.00"
          }
        ],
        "doors": [
          {
            "door": {
              "sku": "102.107.08"
            },
            "handles": [
              {
                "sku": "102.108.00"
              },
              {
                "sku": "102.108.00"
              }
            ]
          }
        ],
        "backwall": {
          "sku": "000.002.08"
        },
        "drawers": [
          {
            "sku": "401.100.147",
            "z": 41.4
          },
          {
            "sku": "401.100.147",
            "z": 60.6
          },
          {
            "sku": "401.100.147",
            "z": 79.8
          }
        ],
        "cluster": 0
      },
      {
        "corpus": {
          "sku": "401.100.05"
        },
        "boards": [
          {
            "sku": "102.103.00",
            "z": 38.3
          },
          {
            "z": 153.5,
            "sku": "102.103.00"
          },
          {
            "z": 191.9,
            "sku": "102.103.00"
          }
        ],
        "doors": [
          {
            "door": {
              "sku": "102.107.00"
            },
            "handles": [
              {
                "sku": "401.100.104"
              },
              {
                "sku": "401.100.104"
              }
            ]
          }
        ],
        "cloth_rails": [
          {
            "sku": "102.119.01",
            "z": 148.4
          }
        ],
        "backwall": {
          "sku": "000.002.02"
        },
        "cluster": 1
      },
      {
        "corpus": {
          "sku": "401.100.04"
        },
        "boards": [
          {
            "sku": "102.103.00",
            "z": 38.3
          },
          {
            "z": 76.7,
            "sku": "102.103.00"
          },
          {
            "z": 115.1,
            "sku": "102.103.00"
          },
          {
            "z": 153.5,
            "sku": "102.103.00"
          },
          {
            "z": 191.9,
            "sku": "102.103.00"
          }
        ],
        "doors": [
          {
            "door": {
              "sku": "102.107.00"
            },
            "handles": [
              {
                "sku": "401.100.104"
              },
              {
                "sku": "401.100.104"
              }
            ]
          }
        ],
        "backwall": {
          "sku": "000.002.08"
        },
        "cluster": 1
      }
    ]
  }
}

=== mycsHQ/mycs-hash/tests/structures/sydetable.json
{
  "camera": {
    "angle": 0,
    "vAngle": 0
  },
  "quality": "hires",
  "stage": "default",
  "structure": {
    "tabletops": {
      "top": { "sku": "301.100.00" }
    },
    "legs": {
      "front_left": {
        "sku": "301.102.03"
      },
      "front_right": {
        "sku": "301.102.03"
      }
    },
    "legs_connector": {
      "bottom": { "sku": "301.102.03" },
      "top_left": { "sku": "301.102.03" },
      "top_right": { "sku": "301.102.03" }
    }
  }
}

=== mycsHQ/mycs-hash/tests/structures/joyn.json
{
  "camera": {
    "angle": -30,
    "vAngle": -30
  },
  "quality": "hires",
  "stage": "default",
  "structure": {
    "container": "joyn",
    "props": {
      "flow": "x"
    },
    "children": [
      {
        "container": "edge-1200-left",
        "props": {
          "flow": "x"
        },
        "children": [
          {
            "container": "edge_submodule",
            "props": {
              "flow": "z"
            },
            "children": [
              {
                "container": "base",
                "props": {
                  "sku": "551.101.00",
                  "cover_sku": "551.310.14",
                  "align_y": "max"
                }
              },
              {
                "container": "sitting_elements",
                "props": {
                  "flow": "y",
                  "align_y": "max"
                },
                "children": [
                  {
                    "container": "cushions",
                    "props": {
                      "flow": "x"
                    },
                    "children": [
                      {
                        "container": "cushion",
                        "props": {
                          "flow": "z"
                        },
                        "children": [
                          {
                            "container": "end_cushion_right",
                            "props": {
                              "sku": "551.142.00",
                              "cover_sku": "551.310.16",
                              "margin_y": [ 0, -16 ]
                            }
                          },
                          {
                            "container": "back_cushion",
                            "props": {
                              "sku": "551.136.00",
                              "cover_sku": "551.310.16",
                              "align_x": "max",
                              "align_y": "max"
                            }
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "container": "backrest",
                    "props": {
                      "sku": "551.111.00",
                      "cover_sku": "551.310.16",
                      "align_x": "max"
                    }
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "container": "extension-800",
        "props": {
          "flow": "z"
        },
        "children": [
          {
            "container": "base-container",
            "props": {
              "flow": "y",
              "align_y": "max"
            },
            "children": [
              {
                "container": "base_extension",
                "props": {
                  "sku": "551.107.00",
                  "cover_sku": "551.310.14",
                  "align_y": "max"
                }
              },
              {
                "container": "base",
                "props": {
                  "sku": "551.100.00",
                  "cover_sku": "551.310.14",
                  "align_y": "max"
                }
              }
            ]
          },
          {
            "container": "sitting_elements",
            "props": {
              "flow": "y",
              "align_y": "max"
            },
            "children": [
              {
                "container": "cushions",
                "props": {
                  "flow": "z"
                },
                "children": [
                  {
                    "container": "l_cushion",
                    "props": {
                      "sku": "551.128.00",
                      "cover_sku": "551.310.16"
                    }
                  },
                  {
                    "container": "back_cushion",
                    "props": {
                      "sku": "551.136.00",
                      "cover_sku": "551.310.16",
                      "align_y": "max"
                    }
                  }
                ]
              },
              {
                "container": "backrest",
                "props": {
                  "sku": "551.111.00",
                  "cover_sku": "551.310.16"
                }
              }
            ]
          }
        ]
      },
      {
        "container": "armrest",
        "props": {
          "flow": "y",
          "align_y": "max"
        },
        "children": [
          {
            "container": "armrest_right",
            "props": {
              "cover_sku": "551.310.14",
              "sku": "551.116.00",
              "margin_x": [ -12, 0 ]
            }
          }
        ]
      }
    ]
  }
}
